config/routes.rb
Rails.application.routes.draw do

  get 'history/index'

  get 'search/index'

  devise_for :users

  root 'search#index'

end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to  :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @searches = current_user.searches
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!,:set_lastfm

  def index
    if params[:search]
      @top_tracks = @lastfm.artist.get_top_tracks(artist: params[:search])
      @artists = @lastfm.artist.search(artist: params[:search])['results']['artistmatches']['artist']
      current_user.searches.create(history: params[:search])
    end
  end

  private

    def set_lastfm
      @lastfm ||= Lastfm.new('b8a8da7b4164232fa03f4930f827112b', '6ce62a3647fb7a2c1422051d8b65eaee')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/history/index.html.erb
<p>&nbsp;

<table class="table">
  <thead>
    <tr>
      <h2>Search History</h2>
    </tr>
  </thead>
  <tbody>
    <% for @search in @searches %>
      <tr>
        <td><%= link_to @search.history, search_index_path(search: @search.history) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LastFm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <h2><%= link_to 'Artist-Search', '/' %></h2>
      </div>

      <ul class="nav navbar-nav navbar-text navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History', history_index_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/search/index.html.erb
<p>&nbsp;

<div class="container">
  <%= form_tag("/", method: "get", class: "col-md-4 form-inline") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Artist", class: "form-control" %>
      <%= submit_tag "Search", class: "btn btn-default" %>
    </div>
  <% end %>
</div>

<div class="container">
  <% if @top_tracks %>
    <h2>Top Recommended Tracks by Artist</h2>
    <table class="table table-bordered table-striped">
      <thead>
          <tr>
            <th>Title</th>
            <th>Duration</th>
            <th>Artist</th>
          </tr>
      </thead>
      <tbody>
        <% for @track in @top_tracks %>
          <tr>
            <td><%= @track['name'] %></td>
            <td><%= @track['duration'] %></td>
            <td><%= @track['artist']['name'] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% if @artists %>
    <h2>Similar artists</h2>
    <% @artists.each_slice(3) do |slice| %>
      <div class="row">
        <% slice.each do |artist| %>
          <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                <img src=<%= artist['image'][3]['content'] %>>
                <div class="caption">
                  <h3><%= artist['name'] %></h3>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>